jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
        path: ~/.gradle/wrapper
        restore-keys: '${{ runner.os }}-gradlew-

          '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build distribution jacocoTestReport -Dpgsql.version=${{ matrix.postgresql
        }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONAR_TOKEN }}
      if: ${{ github.repository == 'alfio-event/alf.io' && matrix.postgresql == '16'}}
      name: upload to sonarcloud
      run: ./gradlew sonarqube
    - continue-on-error: true
      if: ${{ github.repository == 'alfio-event/alf.io' && matrix.postgresql == '10'}}
      name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: build
        retention-days: 5
    strategy:
      matrix:
        postgresql:
        - '10'
        - '16'
  push_image_dev:
    if: ${{ github.repository == 'alfio-event/alf.io' && github.event_name == 'push'
      }}
    name: Push dev image
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Configure Docker
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ secrets.CR_USER }}
    - continue-on-error: true
      name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
    - continue-on-error: true
      name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./dockerize
        platforms: linux/amd64,linux/arm64
        push: false
        tags: 'ghcr.io/alfio-event/alf.io/dev-${{ env.GITHUB_REF_SLUG }}:latest

          '
  push_image_prod:
    if: ${{ github.repository == 'alfio-event/alf.io' && github.event_name == 'push'
      && startsWith(github.ref, 'refs/tags/') }}
    name: Push PROD image
    needs: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
    - continue-on-error: true
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - continue-on-error: true
      name: Configure Docker
      uses: docker/setup-buildx-action@v2
    - continue-on-error: true
      name: Login to Container Registry (GitHub)
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ secrets.CR_USER }}
    - continue-on-error: true
      name: Login to Container Registry (Docker)
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./dockerize
        platforms: linux/amd64,linux/arm64
        push: false
        tags: 'ghcr.io/alfio-event/alf.io/prod:${{github.ref_name}}

          alfio/alf.io:${{github.ref_name}}

          '
name: build
on:
  repository_dispatch:
    types: trigger-ga___build-on-push.yml
