jobs:
  build:
    if: github.repository == 'alfio-event/alf.io'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
        path: ~/.gradle/wrapper
        restore-keys: '${{ runner.os }}-gradlew-

          '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: BrowserStack Env Setup
      uses: browserstack/github-actions/setup-env@master
      with:
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        username: ${{ secrets.BROWSERSTACK_USERNAME }}
    - continue-on-error: true
      env:
        E2E_BROWSER: ${{matrix.browser}}
        E2E_SERVER_APIKEY: ${{ secrets.E2E_SERVER_APIKEY }}
        E2E_SERVER_URL: ${{ secrets.E2E_SERVER_URL }}
      name: Build with Gradle
      run: ./gradlew test -Dspring.profiles.active=travis,e2e --tests NormalFlowE2ETest
    strategy:
      matrix:
        browser:
        - chrome
        - firefox
        - safari
name: E2E Test
on:
  repository_dispatch:
    types: trigger-ga___e2e-test.yml
