jobs:
  build:
    if: github.repository == 'alfio-event/alf.io' && github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Login to Container Registry (GitHub)
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io
        username: ${{ secrets.CR_USER }}
    - continue-on-error: true
      name: Login to Container Registry (Docker)
      uses: docker/login-action@v2
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        MIGRATION_TEST: 'true'
      name: Build with Gradle
      run: ./gradlew test --no-daemon --tests MigrationValidatorTest
name: DB Migration Test
on:
  repository_dispatch:
    types: trigger-ga___migration-test.yml
